// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/About.tsx";
import * as $$1 from "./islands/Hero.tsx";
import * as $$2 from "./islands/Nav.tsx";
import * as $$3 from "./islands/QuickFacts.tsx";
import * as $$4 from "./islands/ScrollSpy.tsx";
import * as $$5 from "./islands/Specialities.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/About.tsx": $$0,
    "./islands/Hero.tsx": $$1,
    "./islands/Nav.tsx": $$2,
    "./islands/QuickFacts.tsx": $$3,
    "./islands/ScrollSpy.tsx": $$4,
    "./islands/Specialities.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
